language: go
script: make test
services:
  - mongodb
install:
  - go get -v ./...
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/onsi/gomega
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin
go:
  - 1.3
  - tip
deploy:
  api_key:
    secure: P7LERXBprrVycognsWARpzWP8PCPND3K6/Kgx4ibnC4xnNKsR7eXmZEqmcoYzO/RZRWgpj8l1gUr+T/s3W5jB/kLIHuWmXggCu+hsLhVIXi9O3c7+MhpOT46ZbqoSxLQ2RlTpSojPok5/CbK9yyA4qnnPG5YBX9lWs8TdgFY++Q=
